version: "3.9"

services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb_cdc
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: etl_db
      MARIADB_USER: etl_user
      MARIADB_PASSWORD: etl_pass

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
